plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.pricetracker'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.pricetracker'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    signingConfigs {
        release {
            storeFile file("../pricetracker.keystore")
            storePassword "pricetracker123"
            keyAlias "pricetracker"
            keyPassword "pricetracker123"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.work:work-runtime:2.10.1'
}
